
name: "Prerelease"
on: 
  push:
    # Run on the main branch
    branches: 
      - "main"
    # Ignore documentation
    paths-ignore:
      - ".idea"
      - "README.md"
      - "docs/**"

jobs:
  pre-release:
    name: "Pre-release"
    runs-on: ubuntu-latest
    steps:
      # clone our repository into the runner
      - uses: actions/checkout@v2
      # install java on the runner
      - name: Setup JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      # make sure that our plugin builds
      - name: Build Project
        run: ./mvn compile
      # build the jars
      - name: Build Jars
        run: ./mvn clean install
      # create a development build
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
                        build/libs/*.jar
